[theme]
base = "light"
primaryColor = "#9B3D34"
backgroundColor = "#F1EFE8"
secondaryBackgroundColor = "#E8E5DC"
textColor = "#202824"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
address = "localhost"
